Latest upstream updates.

diff --git a/.config/taskfiles/ansible/Taskfile-test.yml b/.config/taskfiles/ansible/Taskfile-test.yml
--- a/.config/taskfiles/ansible/Taskfile-test.yml
+++ b/.config/taskfiles/ansible/Taskfile-test.yml
@@ -16,16 +16,23 @@ tasks:
 
   local:test:
     deps:
-      - :ansible:symlink:{{.REPOSITORY_SUBTYPE}}
+      - :symlink:{{.REPOSITORY_SUBTYPE}}
       - :install:python:requirements
     cmds:
-      - true info "Testing Ansible playbook locally"
+      - .config/log info "Testing Ansible playbook locally"
       - cp test/{{OS}}/inventory inventory
       - if [ ! -f ansible.cfg.bak ]; then cp ansible.cfg ansible.cfg.bak; fi
       - cp test/{{OS}}/ansible.cfg ansible.cfg
-      - ansible-playbook --ask-sudo-pass test/{{OS}}/test.yml
+      - |
+        .config/log info 'Prompting for sudo password (required)'
+        {{.PYTHON_HANDLE}}ansible-playbook --ask-sudo-pass test/{{OS}}/test.yml
       - mv ansible.cfg.bak ansible.cfg
       - rm inventory
+
+  molecule:dependencies:
+    cmds:
+      - ansible-galaxy install --ignore-errors -r requirements.yml
+      - task: :symlink:{{.REPOSITORY_SUBTYPE}}
 
   molecule:docker:
     deps:
@@ -49,11 +56,34 @@ tasks:
       `task ansible:test:molecule:docker:matrix`
     cmds:
       - |
-        SCENARIO="docker"
+        SCENARIO="Linux"
         if grep -Ril 'community.general.snap:' ./tasks; then
-          SCENARIO="docker-snap"
+          SCENARIO="Snap"
+          .config/log warn 'Running Docker Molecule tests on the Docker containers that are compatible with `snap` since the role has references to `snap`'
+        else
+          .config/log info 'Running full Docker Molecule test'
         fi
-        molecule test -s "$SCENARIO"
+        MOLECULE_GROUP="$SCENARIO" {{.PYTHON_HANDLE}}molecule test -s docker
+        if [ $? != '0' ]; then
+          .config/log error 'Molecule test finished with errors'
+        else
+          .config/log success 'Successfully ran Docker Molecule test'
+        fi
+
+  molecule:docker:cli:
+    deps:
+      - :install:python:requirements
+      - :install:software:docker
+      - :install:software:sshpass
+    cmds:
+      - |
+        .config/log info 'Running Docker Molecule test on containers in the `{{.CLI_ARGS}}` group'
+        MOLECULE_GROUP="{{.CLI_ARGS}}" {{.PYTHON_HANDLE}}molecule test -s docker
+        if [ $? != '0' ]; then
+          .config/log error 'The `{{.CLI_ARGS}}` Docker Molecule test finished with errors'
+        else
+          .config/log success 'Successfully ran the `{{.CLI_ARGS}}` Docker Molecule test'
+        fi
 
   molecule:docker:matrix:
     deps:
@@ -66,11 +96,117 @@ tasks:
     cmds:
       - mkdir -p molecule/.results
       - |
-        SCENARIO="docker"
+        SCENARIO="Linux"
         if grep -Ril 'community.general.snap:' ./tasks; then
-          SCENARIO="docker-snap"
+          SCENARIO="Snap"
+          .config/log warn 'Running Docker Molecule tests on the Docker containers that are compatible with `snap` since the role has references to `snap`'
+        else
+          .config/log info 'Running full Docker Molecule test'
         fi
-        PY_COLORS=0 molecule test -s "$SCENARIO" 2>&1 | tee "molecule/.results/{{.MOLECULE_DATE}}-$SCENARIO.txt"
+        .config/log info 'Piping results to `molecule/.results/{{.MOLECULE_DATE}}-$SCENARIO.txt` for compatibility chart data'
+        PY_COLORS=0 MOLECULE_GROUP="$SCENARIO" {{.PYTHON_HANDLE}}molecule test -s "$SCENARIO" 2>&1 | tee "molecule/.results/{{.MOLECULE_DATE}}-$SCENARIO.txt"
+        if [ $? != '0' ]; then
+          .config/log error 'There were errors while running the test - results are available at `molecule/.results/{{.MOLECULE_DATE}}-$SCENARIO.txt`'
+        else
+          .config/log success 'Finished running the test - results are available at `molecule/.results/{{.MOLECULE_DATE}}-$SCENARIO.txt`'
+        fi
+
+  molecule:docker:prompt:
+    interactive: true
+    deps:
+      - :install:modules:local
+    cmds:
+      - node .config/scripts/prompts/molecule/docker.js
+
+  molecule:gcp:
+    deps:
+      - :install:python:requirements
+      - :install:software:gcloud
+    cmds:
+      - task: molecule:gcp:preconditions
+      - |
+        .config/log info 'Running Google Cloud Platform Molecule test'
+        {{.PYTHON_HANDLE}}molecule test -s gcp
+        if [ $? != '0' ]; then
+          .config/log error 'Finished running the Google Cloud Platform Molecule test (with errors)'
+        else
+          .config/log success 'Finished running Google Cloud Platform Molecule test'
+        fi
+
+  molecule:local:
+    cmds:
+      - node .config/scripts/prompts/molecule/local.js
+
+  molecule:local:test:
+    cmds:
+      - |
+        .config/log info 'Running Molecule test locally'
+        {{.PYTHON_HANDLE}}molecule test -s local
+        if [ $? != '0' ]; then
+          .config/log error 'There was an error while running the Molecule test locally'
+        else
+          .config/log success 'The local Molecule test was successful!'
+        fi
+
+  molecule:gcp:matrix:
+    deps:
+      - :install:modules:local
+      - :install:software:gcloud
+    vars:
+      MOLECULE_DATE:
+        sh: date '+%Y-%m-%d'
+    cmds:
+      - task: molecule:gcp:preconditions
+      - mkdir -p molecule/.results
+      - |
+        .config/log info 'Piping results to `molecule/.results/{{.MOLECULE_DATE}}-gcp.txt` for compatibility chart data'
+        PY_COLORS=0 {{.PYTHON_HANDLE}}molecule test -s gcp 2>&1 | tee "molecule/.results/{{.MOLECULE_DATE}}-gcp.txt"
+        if [ $? != '0' ]; then
+          .config/log error 'Errors encountered while running the test - results are available at `molecule/.results/{{.MOLECULE_DATE}}-gcp.txt`'
+        else
+          .config/log success 'Finished running the test - results are available at `molecule/.results/{{.MOLECULE_DATE}}-gcp.txt`'
+        fi
+      - |
+        RESULTS="molecule/.results/{{.MOLECULE_DATE}}-gcp.txt"
+        PLATFORM_LENGTH="$(yq e '.platforms | length' molecule/gcp/molecule.yml)"
+        INDEX=0
+        while [ $INDEX -lt $PLATFORM_LENGTH ]; do
+          NAME="$(yq e '.platforms['$INDEX'].name' molecule/gcp/molecule.yml)"
+          ALIAS="$(yq e '.platforms['$INDEX'].alias' molecule/gcp/molecule.yml)"
+          sed -i -- 's/'"$NAME"'/'"$ALIAS"'/g' "$RESULTS"
+          INDEX=$((INDEX+1))
+        done
+
+  molecule:gcp:preconditions:
+    preconditions:
+      - sh: '[ -n "$GCE_SERVICE_ACCOUNT_EMAIL" ]'
+        msg: The GCE_SERVICE_ACCOUNT_EMAIL environment variable must be set (e.g. export
+          GCE_SERVICE_ACCOUNT_EMAIL=molecule@megabyte-labs.iam.gserviceaccount.com).
+      - sh: '[ -n "$GCE_CREDENTIALS_FILE" ]'
+        msg: The GCE_CREDENTIALS_FILE environment variable must be set and pointing to the GCP
+          service account JSON key (e.g. export GCE_CREDENTIALS_FILE=~/.config/gcp.json).
+      - sh: test -f "$GCE_CREDENTIALS_FILE"
+        msg: The GCE_CREDENTIALS_FILE environment variable is defined but is not pointing to a file that exists.
+      - sh: '[ -n "$GCE_PROJECT_ID" ]'
+        msg: The GCE_PROJECT_ID environment variable must be set (e.g. export GCE_PROJECT_ID=megabyte-labs)
+
+  molecule:ssh:cli:
+    deps:
+      - :install:python:requirements
+    cmds:
+      - |
+        molecule test -s remote
+        if [ $? != '0' ]; then
+          .config/log error 'Errors encountered while running the remote Molecule test'
+        else
+          .config/log success 'Successfully ran the Molecule test on the SSH target'
+        fi
+
+  molecule:ssh:prompt:
+    deps:
+      - :install:modules:local
+    cmds:
+      - node .config/scripts/prompts/molecule/ssh.js
 
   molecule:virtualbox:
     deps:
@@ -96,7 +232,30 @@ tasks:
       # yamllint disable-line rule:truthy
       OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
     cmds:
-      - molecule test
+      - |
+        .config/log info 'Running full VirtualBox Molecule E2E test'
+        {{.PYTHON_HANDLE}}molecule test
+        if [ $? != '0' ]; then
+          .config/log error 'Errors were encountered while running the full VirtualBox Molecule E2E test'
+        else
+          .config/log success 'Finished running full VirtualBox Molecule E2E test'
+        fi
+
+  molecule:virtualbox:cli:
+    deps:
+      - :install:python:requirements
+      - :install:software:sshpass
+      - :install:software:vagrant
+      - :install:software:virtualbox
+    cmds:
+      - |
+        .config/log info 'Running VirtualBox Molecule test on platforms in the `{{.CLI_ARGS}}` group'
+        MOLECULE_GROUP="{{.CLI_ARGS}}" {{.PYTHON_HANDLE}}molecule test
+        if [ $? != '0' ]; then
+          .config/log error 'Errors encountered while running the `{{.CLI_ARGS}}` VirtualBox Molecule test'
+        else
+          .config/log success 'Finished running `{{.CLI_ARGS}}` VirtualBox Molecule test'
+        fi
 
   molecule:virtualbox:converge:
     deps:
@@ -116,17 +275,17 @@ tasks:
       `task test:molecule`
 
       **Example usage bypassing prompt:**
-      `task test:molecule -- archlinux`
+      `task test:molecule -- Archlinux`
 
       ## Available scenarios:
 
-      * archlinux
-      * centos
-      * debian
-      * fedora
-      * macos
-      * ubuntu
-      * windows
+      * Archlinux
+      * CentOS
+      * Debian
+      * Fedora
+      * macOS
+      * Ubuntu
+      * Windows
     env:
       # yamllint disable-line rule:truthy
       OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
@@ -136,19 +295,20 @@ tasks:
   molecule:virtualbox:converge:cli:
     cmds:
       - |
-        SCENARIO='{{.CLI_ARGS}}-desktop'
-        if test -d "molecule/$SCENARIO"; then
-          molecule converge -s "$SCENARIO"
+        .config/log info 'Running `{{.CLI_ARGS}}` VirtualBox Molecule converge play - this will leave the VirtualBox instance open for inspection'
+        MOLECULE_GROUP={{.CLI_ARGS}} {{.PYTHON_HANDLE}}molecule converge
+        if [ $? != '0' ]; then
+          .config/log error 'Errors were encountered while running the `{{.CLI_ARGS}}` VirtualBox Molecule converge play'
         else
-          true error "The `$SCENARIO` scenario is not present in the `molecule/` folder"
+          .config/log success 'Finished running the `{{.CLI_ARGS}}` VirtualBox Molecule converge play - you are encouraged to inspect the VM'
         fi
 
   molecule:virtualbox:converge:prompt:
     interactive: true
     deps:
-      - :install:modules:prompt
+      - :install:modules:local
     cmds:
-      - node .config/scripts/prompts/molecule-desktop.js
+      - node .config/scripts/prompts/molecule/desktop.js
 
   molecule:virtualbox:matrix:
     deps:
@@ -161,7 +321,26 @@ tasks:
         sh: date '+%Y-%m-%d'
     cmds:
       - mkdir -p molecule/.results
-      - PY_COLORS=0 molecule test | tee 'molecule/.results/{{.MOLECULE_DATE}}-default.txt'
+      - |
+        .config/log info 'Running full E2E test with VirtualBox - results will be saved to `molecule/.results/{{.MOLECULE_DATE}}-default.txt`'
+        PY_COLORS=0 {{.PYTHON_HANDLE}}molecule test | tee 'molecule/.results/{{.MOLECULE_DATE}}-default.txt'
+        if [ $? != '0' ]; then
+          .config/log error 'Errors were encountered while running the full E2E test - see `molecule/.results/{{.MOLECULE_DATE}}-default.txt` for details'
+        else
+          .config/log success 'Finished running full E2E test - `molecule/.results/{{.MOLECULE_DATE}}-default.txt` contains the results'
+        fi
+
+  molecule:virtualbox:prompt:
+    deps:
+      - :install:modules:local
+    cmds:
+      - node .config/scripts/prompts/molecule/virtualbox.js
+
+  prompt:
+    deps:
+      - :install:modules:local
+    cmds:
+      - node .config/scripts/prompts/molecule/molecule.js
 
   vagrant:
     deps:
@@ -206,11 +385,13 @@ tasks:
 
   vagrant:cli:
     cmds:
-      - vagrant up {{.CLI_ARGS}}
+      - |
+        .config/log info 'Running `vagrant up {{.CLI_ARGS}}`'
+        vagrant up {{.CLI_ARGS}}
 
   vagrant:prompt:
     deps:
-      - :install:modules:prompt
+      - :install:modules:local
     interactive: true
     cmds:
       - node .config/scripts/prompts/vagrant-up.js
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -3,10 +3,10 @@ version: '3'
 
 vars:
   ANSIBLE_LINT_CONFIG: .config/ansible-lint.yml
-  COMMITLINT_CONFIG: .config/commitlint.config.cjs
-  CSPELL_CONFIG: .config/.cspell.json
+  CSPELL_CONFIG: .config/cspell.json
   FLAKE8_CONFIG: .config/flake8.toml
   PRETTIERIGNORE_CONFIG: .config/prettierignore
+  SHELLCHECK_EXCLUDE: SC1091
   YAMLLINT_CONFIG: .config/yamllint.yml
 
 tasks:
@@ -38,7 +38,26 @@ tasks:
 
       For more information, see [Ansible Lint's GitHub page](https://github.com/ansible-community/ansible-lint).
     cmds:
-      - poetry run ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+      - |
+        .config/log info 'Linting the project with ansible-lint'
+        {{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+
+  any:
+    deps:
+      - :install:python:requirements
+    desc: Generic linting of files for things like destroyed-symlinks, merge conflicts, etc.
+    cmds:
+      - '{{.PYTHON_HANDLE}}blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-merge-conflict {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-added-large-files {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-symlinks {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}destroyed-symlinks {{.CLI_ARGS}}'
+
+  codeclimate:
+    deps:
+      - :install:software:codeclimate
+    cmds:
+      - codeclimate
 
   commit:
     deps:
@@ -53,7 +72,16 @@ tasks:
       **Example:**
       `task lint:commit -- 'My commit message'`
     cmds:
-      - if [ ! -z '{{.CLI_ARGS}}' ]; then commitlint -e '{{.CLI_ARGS}}' --config {{.COMMITLINT_CONFIG}}; fi
+      - |
+        if [ ! -z '{{.CLI_ARGS}}' ] && [ '{{.CLI_ARGS}}' != '.git/MERGE_MSG' ]; then
+          cp '{{.CLI_ARGS}}' '{{.CLI_ARGS}}.bak'
+          TMP="$(mktemp)"
+          COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
+          .config/log info 'Linting commit message (with emoji stripped)'
+          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_PACKAGE}} commitlint
+        elif [ '{{.CLI_ARGS}}' == '.git/MERGE_MSG' ]; then
+          .config/log info 'Bypassing commitlint since the message is a merge message'
+        fi
     status:
       - '[[ -z "{{.CLI_ARGS}}" ]]'
     preconditions:
@@ -67,7 +95,7 @@ tasks:
     summary: |
       # Lint Dockerfiles using Hadolint
 
-      Hadolint is a linter for Dockerfiles. This task uses Hadolint to reportrue warnings
+      Hadolint is a linter for Dockerfiles. This task uses Hadolint to report warnings
       and suggestions so that the project is using best practices and is less likely to
       have errors. The task uses Docker to run an ultra-compact container that includes
       Hadolint. Installing Hadolint is done at runtime. The task scans for all files that
@@ -93,6 +121,7 @@ tasks:
       For more information, see [Hadolint's GitHub page](https://github.com/hadolint/hadolint).
     cmds:
       - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}all Dockerfiles{{end}} with a Hadolint Docker image'
         {{if .CLI_ARGS}}
           docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS}}
         {{else}}
@@ -122,16 +151,22 @@ tasks:
       **Example linting specific pattern of files:**
       `task lint:eslint -- '**/*.js'`
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --cache
-        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - >
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with ESLint'
+
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   js:
     deps:
       - :install:modules:local
       - :install:npm:eslint
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts --cache
-        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - >
+        .config/log info 'Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}JavaScript/TypeScript files{{end}} with ESLint'
+
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   lint-staged:
     deps:
@@ -139,7 +174,9 @@ tasks:
       - :install:modules:local
       - :install:python:requirements
     cmds:
-      - '{{.NPX_HANDLE}}lint-staged'
+      - |
+        .config/log info 'Linting changed files'
+        {{.NPX_HANDLE}}lint-staged
 
   packer:
     deps:
@@ -162,9 +199,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
+          .config/log info 'Validating the {{.CLI_ARGS}} Packer template'
           packer validate {{.CLI_ARGS}}
         {{else}}
           for TEMPLATE in *template.json; do
+            .config/log info "Validating the $TEMPLATE Packer template"
             packer validate "$TEMPLATE"
           done
         {{end}}
@@ -187,7 +226,9 @@ tasks:
 
       For more information, see [Prettier's website](https://prettier.io/).
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with Prettier'
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   python:
     deps:
@@ -219,9 +260,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          poetry run flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
+          .config/log info 'Linting {{.CLI_ARGS}} with flake8'
+          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
         {{else}}
-          poetry run flake8 --config {{.FLAKE8_CONFIG}} .
+          .config/log info 'Linting the project with flake8'
+          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} .
         {{end}}
 
   shell:
@@ -253,10 +296,12 @@ tasks:
       For more information, see [Shellcheck's GitHub page](https://github.com/koalaman/shellcheck).
     cmds:
       - |
+        .config/log info 'Linting with Shellcheck'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck {{.CLI_ARGS}}
+          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
         {{else}}
-          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck
+          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
+          -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}}
         {{end}}
 
   spelling:
@@ -266,7 +311,7 @@ tasks:
     summary: |
       # Check for spelling errors in staged files
 
-      Use cspell to check for possible spelling errors using the configuration stored in `.common/.cspell.json`.
+      Use cspell to check for possible spelling errors using the configuration stored in `.config/cspell.json`.
 
       This task is utilized by the pre-commit hook. For more information about cspell, see the
       [cspell NPM page](https://www.npmjs.com/package/cspell).
@@ -285,19 +330,32 @@ tasks:
 
   spelling:cli:
     cmds:
-      - cmd: '{{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}}'
+      - cmd: |
+          set -e
+          EXIT_CODE=0
+          .config/log info 'Running a spell-check with `cspell`'
+          {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
+          if [ "$EXIT_CODE" != '0' ]; then
+            .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+          fi
         ignore_errors: true
 
   spelling:staged:
     deps:
       - :install:npm:cspell
       - :install:software:git
-    env:
-      STAGED_FILES: git diff --cached --name-only
     cmds:
       - cmd: |
-          if [ '{{.STAGED_FILES}}' ]; then
-            {{.NPX_HANDLE}}cspell --no-summary --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} "$STAGED_FILES"
+          STAGED_FILES="$(git diff --cached --name-only)"
+          if [ -n "$STAGED_FILES" ]; then
+            set -e
+            EXIT_CODE=0
+            .config/log info 'Running a spell-check on staged files with `cspell`'
+            # Must not quote $STAGED_FILES
+            {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
+            if [ "$EXIT_CODE" != '0' ]; then
+              .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+            fi
           fi
         ignore_errors: true
 
@@ -317,7 +375,9 @@ tasks:
       **Example scanning specific file:**
       `task lint:toml -- myfile.toml`
     cmds:
-      - poetry run check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid TOML{{else}}the project'\''s TOML files are valid{{end}}'
+        {{.PYTHON_HANDLE}}check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   vagrant:
     deps:
@@ -332,7 +392,9 @@ tasks:
 
       For more information on `vagrant validate`, see the [Vagrant website](https://www.vagrantup.com/docs/cli/validate).
     cmds:
-      - vagrant validate
+      - |
+        .config/log info 'Validating the Vagrantfile'
+        vagrant validate
 
   xml:
     deps:
@@ -350,7 +412,9 @@ tasks:
       **Example scanning specific file:**
       `task lint:xml -- myfile.xml`
     cmds:
-      - poetry run check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid XML{{else}}the project contains only valid XML{{end}}'
+        {{.PYTHON_HANDLE}}check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     deps:
@@ -377,4 +441,6 @@ tasks:
 
       For more information, see the [YAML Lint GitHub page](https://github.com/adrienverge/yamllint).
     cmds:
-      - poetry run yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with `yamllint`'
+        {{.PYTHON_HANDLE}}yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
